---
title: "Untitled"
author: "Zhuojue Wang"
date: '2022-07-04'
output: html_document
---

```{r}
data <- read_csv("topcryptodata.csv", col_types = cols(...1 = col_skip()))


p<- ggplot(data, aes(datetime, cap, color = factor("BTC"))) +
    geom_line() +
    labs(x = "Date",
         y = "Market cap",
         title = paste("BTC", collapse = ", ")) +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      legend.title = element_blank()
    )
ggplotly(p)
```

```{r}
topcryptodata <-
  read_csv("Crypoto/topcryptodata.csv", col_types = cols(...1 = col_skip()))


topcryptodata$datetime %>% class() 
```
```{r}
library(zoo)
plot.corr.timeline <-function(currency1,currency2, mindays,maxdays,data) {
    currency1_return <-
    data %>%
    filter(currency_slug == currency1) %>%
    select(return)
  currency2_return <-
    data %>%
    filter(currency_slug == currency2) %>%
    select(return)
  datetime <- data$datetime
  data_new <- cbind(currency1_return, currency2_return,datetime)
  names(data_new)[1] <- paste("return_", currency1, sep = "")
  names(data_new)[2] <- paste("return_", currency2, sep = "")
  data_new <- data_new %>% as.data.frame()
}
```
```{r}
  fill_na <- rep(NA, 10-1)
  roll_corr <- rollapply(data_new, width=10, function(i) cor(data_new[,1],data_new[,2]),by.column=FALSE)
  data_new$corr <-  append(fill_na ,roll_corr)
  data_new
}

          #cor(data_new[max(1, i - maxdays):i, 1], data_new[max(1, i - maxdays):i, 2])
    p <- ggplot(data_new[-c(1:10),], aes(datetime, corr))
    p + geom_line() + labs(
      x = "Date",
      y = "Correlation",
      title = paste("Correlation timeline: ", paste(c(
        currency1, currency2
      ), collapse = ", "))
    )
  }
```

```{r}
data_new <- plot.corr.timeline("BTC", "ETH", 10, 90,topcryptodata[topcryptodata$datetime >as.Date("2017-12-31 UTC"), ])
data_new <- data_new %>% head(12)
class(data_new[,1])
class(data_new[,2])
cor(data_new[,1],data_new[,2])
rollapply(data_new, width=3, function(x) cor(x[,1],x[,2]),by.column=FALSE)
```


```{r}
data <- data.frame(month=1:15,
                   x=c(13, 15, 16, 15, 17, 20, 22, 24, 25, 26, 23, 24, 23, 22, 20),
                   y=c(22, 24, 23, 27, 26, 26, 27, 30, 33, 32, 27, 25, 28, 26, 28),
                   z=c(21, 24, 23, 27, 26, 26, 27, 30, 33, 32, 27, 25, 28, 26, 28))
class(data)
class(data[,2])
rollapply(data, width=3, function(x) cor(x[,2],x[,4]), by.column=FALSE)
```
```{r}

```


```{r}
data <- plot.corr.timeline("BTC", "ETH", 10, 90,topcryptodata[topcryptodata$datetime >as.Date("2017-12-31 UTC"), ])
data
fill_na <- rep(NA, 10-1)
fill_na
corr <- append(fill_na, rollapply(data, width=10, function(i) cor(data[,1],data[,2]), by.column=FALSE))
corr
#data <- data[-c(1:10),]
data 

p <- ggplot(data, aes(datetime, corr))
    p + geom_line() + labs(
      x = "Date",
      y = "Correlation",
      title = "cor")
#sapply(1:nrow(data),FUN = function(i)
#cor(data[max(1, i - 90):i, 1], data[max(1, i - 90):i, 2]))
```
```{r}
topcryptodata 
```

```{r}
#my_map <- hcmap("custom/world-highres3")
#saveRDS(my_map, "my_map.RDS")
readRDS("my_map.RDS")
```



